# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailmux < Formula
  desc "Run multiple isolated Tailscale tailnets at once, routed by hostname suffix"
  homepage "https://tailmux.app"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://assets.tailmux.app/tailmux_0.2.0_darwin_amd64.tar.gz"
      sha256 "deb6ae1675821204b7bd931c6ad86819aa7c871c8b34aacd919d650b28ef4fa0"

      define_method(:install) do
        bin.install "tailmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://assets.tailmux.app/tailmux_0.2.0_darwin_arm64.tar.gz"
      sha256 "c09f898d51aecbc372ca8ff54ebab0177805310d5cf731d2819bb5b8a2c1e3eb"

      define_method(:install) do
        bin.install "tailmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://assets.tailmux.app/tailmux_0.2.0_linux_amd64.tar.gz"
      sha256 "17e9461936e2afa08f8992325105784c38b444f856ede8d00c54a2f4800f6b94"
      define_method(:install) do
        bin.install "tailmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://assets.tailmux.app/tailmux_0.2.0_linux_arm64.tar.gz"
      sha256 "916c96efa66b48186981a5933f741807a0ab4bcc7e74e2fec8ee73c07704693d"
      define_method(:install) do
        bin.install "tailmux"
      end
    end
  end

  def caveats
    <<~EOS
      TailMux requires a one-time license: https://tailmux.app/pricing

      On macOS, prefer the cask — it installs the menu-bar app with this
      CLI bundled:
        brew install --cask cq-fabrication/tap/tailmux
    EOS
  end

  test do
    system "#{bin}/tailmux", "version"
  end
end
