# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailmux < Formula
  desc "Run multiple isolated Tailscale tailnets at once, routed by hostname suffix"
  homepage "https://tailmux.app"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://assets.tailmux.app/tailmux_0.1.1_darwin_amd64.tar.gz"
      sha256 "6a00e6583409eeddbf324985cf460790052fa132a03a0be90b57c9cc3aac86e8"

      define_method(:install) do
        bin.install "tailmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://assets.tailmux.app/tailmux_0.1.1_darwin_arm64.tar.gz"
      sha256 "dc002eb26ac0ca4baac1368e405662a63ded2457155f4f9cd18827e6aecd7dfd"

      define_method(:install) do
        bin.install "tailmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://assets.tailmux.app/tailmux_0.1.1_linux_amd64.tar.gz"
      sha256 "23ab165dbb5fc5862521c0bcca5fe79c01542a8e670cdb82a106a4ce17b42258"
      define_method(:install) do
        bin.install "tailmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://assets.tailmux.app/tailmux_0.1.1_linux_arm64.tar.gz"
      sha256 "6c39bf597a92298f8d9f653386db5f09fb455b3f53994121eae60fb724891683"
      define_method(:install) do
        bin.install "tailmux"
      end
    end
  end

  def caveats
    <<~EOS
      TailMux requires a one-time license: https://tailmux.app/pricing

      On macOS, prefer the cask — it installs the menu-bar app with this
      CLI bundled:
        brew install --cask cq-fabrication/tap/tailmux
    EOS
  end

  test do
    system "#{bin}/tailmux", "version"
  end
end
