# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailmux < Formula
  desc "Run multiple isolated Tailscale tailnets at once, routed by hostname suffix"
  homepage "https://tailmux.app"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://assets.tailmux.app/tailmux_0.1.0_darwin_amd64.tar.gz"
      sha256 "82ab01be043e9ab3d49fb48a412e9e36e4d826f1bb50100fa0e4acead98f3cd0"

      define_method(:install) do
        bin.install "tailmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://assets.tailmux.app/tailmux_0.1.0_darwin_arm64.tar.gz"
      sha256 "691d72159ccb1a899ce63352fe1d579cbe6df81680e38b742f39633a129fc4df"

      define_method(:install) do
        bin.install "tailmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://assets.tailmux.app/tailmux_0.1.0_linux_amd64.tar.gz"
      sha256 "82ee0faad72d9a2066ae3d9c32cf35e8a9a39cdbf56146f5ff27885daedea848"
      define_method(:install) do
        bin.install "tailmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://assets.tailmux.app/tailmux_0.1.0_linux_arm64.tar.gz"
      sha256 "765d6cc435d72459a7c1ce2170d8afe571240f8157033036004b74f3c0ad4469"
      define_method(:install) do
        bin.install "tailmux"
      end
    end
  end

  def caveats
    <<~EOS
      TailMux requires a one-time license: https://tailmux.app/pricing

      On macOS, prefer the cask — it installs the menu-bar app with this
      CLI bundled:
        brew install --cask cq-fabrication/tap/tailmux
    EOS
  end

  test do
    system "#{bin}/tailmux", "version"
  end
end
